
* todo2org 
Creating org-mode entries from email messages with a "To"-address syntax similar to the org date/time prompt.

** Intention

todo2org can be used to create org-mode entries with timestamps from email messages. I use a dedicated mail domain (@todo.example) with catch-all activated, such that all mail is delivered to a single mailbox, regardless of the specific "To" address. Mail is then handed over to todo2org, which appends an org-mode entry to my ~inbox.org~ similar to MobileOrg. I can then refile those entries to wherever they belong. This way I can get all ToDos which pop up via email out of my inbox, and I can even set reminders to follow-up on specific emails by Bcc-ing them to a certain address. 

*** Example

If today is July 17, 2014, and I send the following email to "mo#10@todo.example" (which is a shortcut for "next monday at 10am"), todo2org will output the following org-mode entry

#+BEGIN_EXAMPLE
% cat testmail.txt 
From: Thomas Quaritsch <quaritsch@gmail.com>
Date: Thu, 17 Jul 2014 13:07:20 +0200
Message-ID: <CAAaab3XnagC1=xBpMr4rd-NCGf4eeX_=_mg_d4rHLy+bqFmLAw@mail.bla.blubb>
Subject: test 3
To: mo#10@todo.example
Content-Type: text/plain; charset=UTF-8


test 3
foobar 4
asdf 5

-- 
Thomas Quaritsch

% ./todo2org.py -i testmail.txt
 * test 3
SCHEDULED: <2014-07-21 Mon 10:00>

From: Thomas Quaritsch <quaritsch@gmail.com>
To: mo#10@todo.example
Date: Thu, 17 Jul 2014 13:07:20 +0200
Subject: test 3

test 3
foobar 4
asdf 5
#+END_EXAMPLE



** Usage

Depending on your mail and org-mode setup, you can either configure your mail delivery agent to run todo2org directly, or you use a mail retriever like getmail[1] on your computer to fetch the messages from your catch-all mailbox and pass them to todo2org. 

todo2org is a Python 2 program called as follows. 

#+BEGIN_EXAMPLE
usage: todo2org.py [-h] [-i inputfile] [-o outputfile]
                   [--append | --no-append] [--encoding enc]

Append email messages with special "To"-addresses to an org-mode file.

optional arguments:
  -h, --help      show this help message and exit
  -i inputfile    file to read the email from (default: stdin)
  -o outputfile   org-mode file to write the message content to (default:
                  stdout)
  --append, -a    append the org-mode entry to the given file (default: True)
  --no-append     overwrite the given output file (default: False)
  --encoding enc  output encoding to use, see list of available encodings at
                  https://docs.python.org/2/library/codecs.html#standard-
                  encodings (default: utf8)
#+END_EXAMPLE

If you do not specify any parameters, it reads mail from standard input and prints the org-mode entry to standard output encoded in UTF-8. 

*** Supported Recipient Address Formats

The address of the "To" field of processed emails is in the format dayspec ~#~ timespec ~@~ domain, where dayspec is one of the following

- ~today~, ~tomorrow~ (can be abbreviated as to and tom)
- ~monday~, ~tuesday~, ~wednesday~, ~thursday~, ~friday~, ~saturday~, ~sunday~ (any abbreviation up to ~mo~, ~tu~, ~we~, ~th~, ~fr~, ~sa~, ~su~ can be used)
- ~XX~ (an integer specifying a day of the current (or next, if is past the current) day of month, e.g. on May 25, ~10~ would mean June 10. 
- ~Xd~ (an integer followed by "d", specifying today + X days, e.g. ~2d~ means two days from now)
- ~Xw~ (same with weeks)
- ~Xm~ (same with months)
- ~Xy~ (same with years)
- ~XX-YY~ (two integers separated by hypen, ~XX~ specifies the month and ~YY~ the day of the month, e.g. ~7-17~ would mean July 17)
- ~monthXX~ (where month is either ~january~, ~february~, ...,  ~december~, any abbreviation up to ~jan~, ~feb~, ..., ~dec~ can be used)
- ~ZZZZ-XX-YY~ (a full date in ISO format)

timespec may be
- ~hhmm~ (specifies hours and minutes)
- ~hh~ (specifies hours only, minutes = 0)

For further examples see the documentation string of ~get_date_by_relative_str~ in ~todo2org.py~.

** License

Copyright 2014 Thomas Quaritsch, t.quaritsch@gmail.com
 
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

* Author 

Thomas Quaritsch [[mailto:t.quaritsch@gmail.com][t.quaritsch@gmail.com]]

* Footnotes

[1] http://pyropus.ca/software/getmail/

